export const tickers = ['AAPL',
'MSFT',
'AMZN',
'GOOGL',
'GOOG',
'TSLA',
'NVDA',
'BRKB',
'FB',
'JPM',
'UNH',
'JNJ',
'V',
'PG',
'HD',
'BAC',
'MA',
'XOM',
'DIS',
'PFE',
'CVX',
'ABBV',
'AVGO',
'KO',
'WFC',
'PEP',
'CSCO',
'ADBE',
'COST',
'VZ',
'CMCSA',
'TMO',
'ABT',
'CRM',
'ACN',
'AMD',
'INTC',
'MRK',
'QCOM',
'LLY',
'WMT',
'MCD',
'NKE',
'NFLX',
'T',
'DHR',
'PM',
'UNP',
'UPS',
'LOW',
'LIN',
'TXN',
'BMY',
'INTU',
'MS',
'NEE',
'RTX',
'MDT',
'PYPL',
'CVS',
'SCHW',
'C',
'HON',
'ORCL',
'AMGN',
'AMAT',
'AXP',
'GS',
'BA',
'COP',
'NOW',
'IBM',
'BLK',
'DE',
'SBUX',
'GE',
'CAT',
'ANTM',
'BKNG',
'MU',
'PLD',
'AMT',
'ISRG',
'TGT',
'LMT',
'ZTS',
'SPGI',
'MO',
'MDLZ',
'MMM',
'PNC',
'CB',
'ADI',
'SYK',
'TFC',
'ADP',
'CME',
'LRCX',
'TJX',
'USB',
'BDX',
'MMC',
'GILD',
'CSX',
'DUK',
'CI',
'CHTR',
'TMUS',
'GM',
'CCI',
'EL',
'F',
'ICE',
'EW',
'SO',
'COF',
'NSC',
'CL',
'REGN',
'SHW',
'EOG',
'FCX',
'ATVI',
'D',
'ITW',
'AON',
'FIS',
'BSX',
'ETN',
'PGR',
'EQIX',
'VRTX',
'KLAC',
'HCA',
'FISV',
'NOC',
'FDX',
'EMR',
'SLB',
'WM',
'APD',
'HUM',
'ILMN',
'PSA',
'MCO',
'MRNA',
'NXPI',
'MET',
'ADSK',
'NEM',
'AIG',
'PXD',
'MAR',
'GD',
'CNC',
'TEL',
'MPC',
'JCI',
'BK',
'CTSH',
'DG',
'SNPS',
'ROP',
'SPG',
'DOW',
'APH',
'ECL',
'ORLY',
'MSCI',
'PRU',
'KMB',
'HLT',
'CMG',
'IQV',
'FTNT',
'IDXX',
'INFO',
'SYY',
'HPQ',
'ADM',
'BAX',
'AEP',
'SRE',
'DD',
'LHX',
'TRV',
'MCK',
'GPN',
'MCHP',
'A',
'EXC',
'AZO',
'GIS',
'CDNS',
'DXCM',
'CARR',
'AFL',
'PH',
'APTV',
'ALGN',
'PSX',
'DLR',
'PAYX',
'EA',
'O',
'EBAY',
'SIVB',
'DFS',
'MSI',
'CTVA',
'STT',
'TT',
'YUM',
'WMB',
'VLO',
'STZ',
'PPG',
'ALL',
'XEL',
'WELL',
'OXY',
'AMP',
'NUE',
'WBA',
'IFF',
'ROST',
'TDG',
'RMD',
'FITB',
'SBAC',
'OTIS',
'MTCH',
'CBRE',
'AVB',
'TROW',
'KMI',
'CTAS',
'MTD',
'PCAR',
'PEG',
'DVN',
'GLW',
'BIIB',
'AJG',
'CMI',
'ROK',
'KR',
'WY',
'VRSK',
'KEYS',
'FRC',
'DLTR',
'EXPE',
'MNST',
'AME',
'BLL',
'FAST',
'TWTR',
'HSY',
'EQR',
'ANET',
'HAL',
'ED',
'WST',
'DAL',
'ANSS',
'ES',
'ALB',
'WEC',
'LUV',
'ODFL',
'OKE',
'WTW',
'TSN',
'DHI',
'CERN',
'CPRT',
'EFX',
'SWK',
'AWK',
'LYB',
'EPAM',
'ARE',
'NTRS',
'EXR',
'HES',
'LH',
'ZBH',
'CDW',
'LEN',
'BKR',
'TSCO',
'VMC',
'KEY',
'MKC',
'RSG',
'IT',
'KHC',
'SYF',
'HIG',
'RF',
'MLM',
'MAA',
'HBAN',
'CHD',
'MTB',
'FTV',
'CFG',
'URI',
'DOV',
'ZBRA',
'SWKS',
'BBY',
'PKI',
'STE',
'EIX',
'HPE',
'DTE',
'IR',
'STX',
'FE',
'VIAC',
'FANG',
'AEE',
'PPL',
'VRSN',
'ABC',
'SBNY',
'RJF',
'ULTA',
'ETR',
'ENPH',
'ESS',
'GWW',
'MPWR',
'VTR',
'NDAQ',
'DRE',
'NTAP',
'FLT',
'VFC',
'TDY',
'WAT',
'TTWO',
'COO',
'TYL',
'TER',
'DRI',
'RCL',
'PFG',
'ETSY',
'CTRA',
'OMC',
'VTRS',
'GPC',
'KMX',
'POOL',
'IP',
'EXPD',
'AMCR',
'CCL',
'CINF',
'AKAM',
'GRMN',
'CMS',
'HOLX',
'MGM',
'CZR',
'CE',
'CLX',
'GNRC',
'PEAK',
'TRMB',
'BR',
'WDC',
'BXP',
'CAG',
'CTLT',
'WAB',
'CNP',
'NLOK',
'NVR',
'MOS',
'EMN',
'PAYC',
'K',
'XYL',
'JBHT',
'UAL',
'MRO',
'J',
'TECH',
'DGX',
'DPZ',
'UDR',
'TXT',
'LVS',
'LYV',
'CRL',
'CEG',
'CF',
'BRO',
'FDS',
'CAH',
'TFX',
'AVY',
'FMC',
'QRVO',
'LKQ',
'SJM',
'BBWI',
'PWR',
'IEX',
'MKTX',
'MAS',
'KIM',
'AES',
'IPG',
'AAP',
'LNT',
'PKG',
'EVRG',
'FOXA',
'SEDG',
'ABMD',
'RHI',
'ATO',
'HWM',
'CMA',
'HRL',
'HST',
'BIO',
'CBOE',
'LNC',
'IRM',
'INCY',
'PHM',
'WHR',
'CTXS',
'WRB',
'WRK',
'L',
'JKHY',
'NDSN',
'FBHS',
'HAS',
'XRAY',
'AAL',
'BFB',
'FFIV',
'PTC',
'RE',
'APA',
'ZION',
'LDOS',
'CHRW',
'SNA',
'HSIC',
'TPR',
'JNPR',
'NI',
'BWA',
'ALLE',
'WYNN',
'UHS',
'REG',
'NWL',
'PNR',
'GL',
'AIZ',
'LW',
'CDAY',
'SEE',
'AOS',
'NRG',
'DXC',
'TAP',
'LUMN',
'NWSA',
'PBCT',
'CPB',
'OGN',
'DISCK',
'BEN',
'FRT',
'PENN',
'MHK',
'NCLH',
'IVZ',
'DISH',
'DVA',
'PNW',
'ALK',
'HII',
'PVH',
'ROL',
'VNO',
'NLSN',
'RL',
'FOX',
'IPGP',
'DISCA',
'UAA',
'UA',
'NWS'
]

const companyNames = ['Apple Inc',
'Microsoft Corporation',
'Amazoncom Inc',
'Alphabet Inc Class A',
'Alphabet Inc Class C',
'Tesla Inc',
'NVIDIA Corporation',
'Berkshire Hathaway Inc Class B',
'Meta Platforms Inc Class A',
'JPMorgan Chase & Co',
'UnitedHealth Group Incorporated',
'Johnson & Johnson',
'Visa Inc Class A',
'Procter & Gamble Company',
'Home Depot Inc',
'Bank of America Corp',
'Mastercard Incorporated Class A',
'Exxon Mobil Corporation',
'Walt Disney Company',
'Pfizer Inc',
'Chevron Corporation',
'AbbVie Inc',
'Broadcom Inc',
'Coca-Cola Company',
'Wells Fargo & Company',
'PepsiCo Inc',
'Cisco Systems Inc',
'Adobe Inc',
'Costco Wholesale Corporation',
'Verizon Communications Inc',
'Comcast Corporation Class A',
'Thermo Fisher Scientific Inc',
'Abbott Laboratories',
'salesforcecom inc',
'Accenture Plc Class A',
'Advanced Micro Devices Inc',
'Intel Corporation',
'Merck & Co Inc',
'Qualcomm Inc',
'Eli Lilly and Company',
'Walmart Inc',
'McDonalds Corporation',
'NIKE Inc Class B',
'Netflix Inc',
'AT&T Inc',
'Danaher Corporation',
'Philip Morris International Inc',
'Union Pacific Corporation',
'United Parcel Service Inc Class B',
'Lowes Companies Inc',
'Linde plc',
'Texas Instruments Incorporated',
'Bristol-Myers Squibb Company',
'Intuit Inc',
'Morgan Stanley',
'NextEra Energy Inc',
'Raytheon Technologies Corporation',
'Medtronic Plc',
'PayPal Holdings Inc',
'CVS Health Corporation',
'Charles Schwab Corporation',
'Citigroup Inc',
'Honeywell International Inc',
'Oracle Corporation',
'Amgen Inc',
'Applied Materials Inc',
'American Express Company',
'Goldman Sachs Group Inc',
'Boeing Company',
'ConocoPhillips',
'ServiceNow Inc',
'International Business Machines Corporation',
'BlackRock Inc',
'Deere & Company',
'Starbucks Corporation',
'General Electric Company',
'Caterpillar Inc',
'Anthem Inc',
'Booking Holdings Inc',
'Micron Technology Inc',
'Prologis Inc',
'American Tower Corporation',
'Intuitive Surgical Inc',
'Target Corporation',
'Lockheed Martin Corporation',
'Zoetis Inc Class A',
'S&P Global Inc',
'Altria Group Inc',
'Mondelez International Inc Class A',
'3M Company',
'PNC Financial Services Group Inc',
'Chubb Limited',
'Analog Devices Inc',
'Stryker Corporation',
'Truist Financial Corporation',
'Automatic Data Processing Inc',
'CME Group Inc Class A',
'Lam Research Corporation',
'TJX Companies Inc',
'US Bancorp',
'Becton Dickinson and Company',
'Marsh & McLennan Companies Inc',
'Gilead Sciences Inc',
'CSX Corporation',
'Duke Energy Corporation',
'Cigna Corporation',
'Charter Communications Inc Class A',
'T-Mobile US Inc',
'General Motors Company',
'Crown Castle International Corp',
'Estee Lauder Companies Inc Class A',
'Ford Motor Company',
'Intercontinental Exchange Inc',
'Edwards Lifesciences Corporation',
'Southern Company',
'Capital One Financial Corporation',
'Norfolk Southern Corporation',
'Colgate-Palmolive Company',
'Regeneron Pharmaceuticals Inc',
'Sherwin-Williams Company',
'EOG Resources Inc',
'Freeport-McMoRan Inc',
'Activision Blizzard Inc',
'Dominion Energy Inc',
'Illinois Tool Works Inc',
'Aon Plc Class A',
'Fidelity National Information Services Inc',
'Boston Scientific Corporation',
'Eaton Corp Plc',
'Progressive Corporation',
'Equinix Inc',
'Vertex Pharmaceuticals Incorporated',
'KLA Corporation',
'HCA Healthcare Inc',
'Fiserv Inc',
'Northrop Grumman Corporation',
'FedEx Corporation',
'Emerson Electric Co',
'Schlumberger NV',
'Waste Management Inc',
'Air Products and Chemicals Inc',
'Humana Inc',
'Illumina Inc',
'Public Storage',
'Moodys Corporation',
'Moderna Inc',
'NXP Semiconductors NV',
'MetLife Inc',
'Autodesk Inc',
'Newmont Corporation',
'American International Group Inc',
'Pioneer Natural Resources Company',
'Marriott International Inc Class A',
'General Dynamics Corporation',
'Centene Corporation',
'TE Connectivity Ltd',
'Marathon Petroleum Corporation',
'Johnson Controls International plc',
'Bank of New York Mellon Corporation',
'Cognizant Technology Solutions Corporation Class A',
'Dollar General Corporation',
'Synopsys Inc',
'Roper Technologies Inc',
'Simon Property Group Inc',
'Dow Inc',
'Amphenol Corporation Class A',
'Ecolab Inc',
'OReilly Automotive Inc',
'MSCI Inc Class A',
'Prudential Financial Inc',
'Kimberly-Clark Corporation',
'Hilton Worldwide Holdings Inc',
'Chipotle Mexican Grill Inc',
'IQVIA Holdings Inc',
'Fortinet Inc',
'IDEXX Laboratories Inc',
'IHS Markit Ltd',
'Sysco Corporation',
'HP Inc',
'Archer-Daniels-Midland Company',
'Baxter International Inc',
'American Electric Power Company Inc',
'Sempra Energy',
'DuPont de Nemours Inc',
'L3Harris Technologies Inc',
'Travelers Companies Inc',
'McKesson Corporation',
'Global Payments Inc',
'Microchip Technology Incorporated',
'Agilent Technologies Inc',
'Exelon Corporation',
'AutoZone Inc',
'General Mills Inc',
'Cadence Design Systems Inc',
'DexCom Inc',
'Carrier Global Corp',
'Aflac Incorporated',
'Parker-Hannifin Corporation',
'Aptiv PLC',
'Align Technology Inc',
'Phillips 66',
'Digital Realty Trust Inc',
'Paychex Inc',
'Electronic Arts Inc',
'Realty Income Corporation',
'eBay Inc',
'SVB Financial Group',
'Discover Financial Services',
'Motorola Solutions Inc',
'Corteva Inc',
'State Street Corporation',
'Trane Technologies plc',
'Yum! Brands Inc',
'Williams Companies Inc',
'Valero Energy Corporation',
'Constellation Brands Inc Class A',
'PPG Industries Inc',
'Allstate Corporation',
'Xcel Energy Inc',
'Welltower Inc',
'Occidental Petroleum Corporation',
'Ameriprise Financial Inc',
'Nucor Corporation',
'Walgreens Boots Alliance Inc',
'International Flavors & Fragrances Inc',
'Ross Stores Inc',
'TransDigm Group Incorporated',
'ResMed Inc',
'Fifth Third Bancorp',
'SBA Communications Corp Class A',
'Otis Worldwide Corporation',
'Match Group Inc',
'CBRE Group Inc Class A',
'AvalonBay Communities Inc',
'T Rowe Price Group',
'Kinder Morgan Inc Class P',
'Cintas Corporation',
'Mettler-Toledo International Inc',
'PACCAR Inc',
'Public Service Enterprise Group Inc',
'Devon Energy Corporation',
'Corning Inc',
'Biogen Inc',
'Arthur J Gallagher & Co',
'Cummins Inc',
'Rockwell Automation Inc',
'Kroger Co',
'Weyerhaeuser Company',
'Verisk Analytics Inc',
'Keysight Technologies Inc',
'First Republic Bank',
'Dollar Tree Inc',
'Expedia Group Inc',
'Monster Beverage Corporation',
'AMETEK Inc',
'Ball Corporation',
'Fastenal Company',
'Twitter Inc',
'Hershey Company',
'Equity Residential',
'Arista Networks Inc',
'Halliburton Company',
'Consolidated Edison Inc',
'West Pharmaceutical Services Inc',
'Delta Air Lines Inc',
'ANSYS Inc',
'Eversource Energy',
'Albemarle Corporation',
'WEC Energy Group Inc',
'Southwest Airlines Co',
'Old Dominion Freight Line Inc',
'ONEOK Inc',
'Willis Towers Watson Public Limited Company',
'Tyson Foods Inc Class A',
'DR Horton Inc',
'Cerner Corporation',
'Copart Inc',
'Equifax Inc',
'Stanley Black & Decker Inc',
'American Water Works Company Inc',
'LyondellBasell Industries NV',
'EPAM Systems Inc',
'Alexandria Real Estate Equities Inc',
'Northern Trust Corporation',
'Extra Space Storage Inc',
'Hess Corporation',
'Laboratory Corporation of America Holdings',
'Zimmer Biomet Holdings Inc',
'CDW Corp',
'Lennar Corporation Class A',
'Baker Hughes Company Class A',
'Tractor Supply Company',
'Vulcan Materials Company',
'KeyCorp',
'McCormick & Company Incorporated',
'Republic Services Inc',
'Gartner Inc',
'Kraft Heinz Company',
'Synchrony Financial',
'Hartford Financial Services Group Inc',
'Regions Financial Corporation',
'Martin Marietta Materials Inc',
'Mid-America Apartment Communities Inc',
'Huntington Bancshares Incorporated',
'Church & Dwight Co Inc',
'M&T Bank Corporation',
'Fortive Corp',
'Citizens Financial Group Inc',
'United Rentals Inc',
'Dover Corporation',
'Zebra Technologies Corporation Class A',
'Skyworks Solutions Inc',
'Best Buy Co Inc',
'PerkinElmer Inc',
'STERIS Plc',
'Edison International',
'Hewlett Packard Enterprise Co',
'DTE Energy Company',
'Ingersoll Rand Inc',
'Seagate Technology Holdings PLC',
'FirstEnergy Corp',
'ViacomCBS Inc Class B',
'Diamondback Energy Inc',
'Ameren Corporation',
'PPL Corporation',
'VeriSign Inc',
'AmerisourceBergen Corporation',
'Signature Bank',
'Raymond James Financial Inc',
'Ulta Beauty Inc',
'Entergy Corporation',
'Enphase Energy Inc',
'Essex Property Trust Inc',
'WW Grainger Inc',
'Monolithic Power Systems Inc',
'Ventas Inc',
'Nasdaq Inc',
'Duke Realty Corporation',
'NetApp Inc',
'FLEETCOR Technologies Inc',
'VF Corporation',
'Teledyne Technologies Incorporated',
'Waters Corporation',
'Take-Two Interactive Software Inc',
'Cooper Companies Inc',
'Tyler Technologies Inc',
'Teradyne Inc',
'Darden Restaurants Inc',
'Royal Caribbean Group',
'Principal Financial Group Inc',
'Etsy Inc',
'Coterra Energy Inc',
'Omnicom Group Inc',
'Viatris Inc',
'Genuine Parts Company',
'CarMax Inc',
'Pool Corporation',
'International Paper Company',
'Expeditors International of Washington Inc',
'Amcor PLC',
'Carnival Corporation',
'Cincinnati Financial Corporation',
'Akamai Technologies Inc',
'Garmin Ltd',
'CMS Energy Corporation',
'Hologic Inc',
'MGM Resorts International',
'Caesars Entertainment Inc',
'Celanese Corporation',
'Clorox Company',
'Generac Holdings Inc',
'Healthpeak Properties Inc',
'Trimble Inc',
'Broadridge Financial Solutions Inc',
'Western Digital Corporation',
'Boston Properties Inc',
'Conagra Brands Inc',
'Catalent Inc',
'Westinghouse Air Brake Technologies Corporation',
'CenterPoint Energy Inc',
'NortonLifeLock Inc',
'NVR Inc',
'Mosaic Company',
'Eastman Chemical Company',
'Paycom Software Inc',
'Kellogg Company',
'Xylem Inc',
'JB Hunt Transport Services Inc',
'United Airlines Holdings Inc',
'Marathon Oil Corporation',
'Jacobs Engineering Group Inc',
'Bio-Techne Corporation',
'Quest Diagnostics Incorporated',
'Dominos Pizza Inc',
'UDR Inc',
'Textron Inc',
'Las Vegas Sands Corp',
'Live Nation Entertainment Inc',
'Charles River Laboratories International Inc',
'Constellation Energy Corporation',
'CF Industries Holdings Inc',
'Brown & Brown Inc',
'FactSet Research Systems Inc',
'Cardinal Health Inc',
'Teleflex Incorporated',
'Avery Dennison Corporation',
'FMC Corporation',
'Qorvo Inc',
'LKQ Corporation',
'JM Smucker Company',
'Bath & Body Works Inc',
'Quanta Services Inc',
'IDEX Corporation',
'MarketAxess Holdings Inc',
'Masco Corporation',
'Kimco Realty Corporation',
'AES Corporation',
'Interpublic Group of Companies Inc',
'Advance Auto Parts Inc',
'Alliant Energy Corp',
'Packaging Corporation of America',
'Evergy Inc',
'Fox Corporation Class A',
'SolarEdge Technologies Inc',
'ABIOMED Inc',
'Robert Half International Inc',
'Atmos Energy Corporation',
'Howmet Aerospace Inc',
'Comerica Incorporated',
'Hormel Foods Corporation',
'Host Hotels & Resorts Inc',
'Bio-Rad Laboratories Inc Class A',
'Cboe Global Markets Inc',
'Lincoln National Corporation',
'Iron Mountain Inc',
'Incyte Corporation',
'PulteGroup Inc',
'Whirlpool Corporation',
'Citrix Systems Inc',
'W R Berkley Corporation',
'WestRock Company',
'Loews Corporation',
'Jack Henry & Associates Inc',
'Nordson Corporation',
'Fortune Brands Home & Security Inc',
'Hasbro Inc',
'DENTSPLY SIRONA Inc',
'American Airlines Group Inc',
'Brown-Forman Corporation Class B',
'F5 Inc',
'PTC Inc',
'Everest Re Group Ltd',
'APA Corp',
'Zions Bancorporation NA',
'Leidos Holdings Inc',
'CH Robinson Worldwide Inc',
'Snap-on Incorporated',
'Henry Schein Inc',
'Tapestry Inc',
'Juniper Networks Inc',
'NiSource Inc',
'BorgWarner Inc',
'Allegion PLC',
'Wynn Resorts Limited',
'Universal Health Services Inc Class B',
'Regency Centers Corporation',
'Newell Brands Inc',
'Pentair plc',
'Globe Life Inc',
'Assurant Inc',
'Lamb Weston Holdings Inc',
'Ceridian HCM Holding Inc',
'Sealed Air Corporation',
'A O Smith Corporation',
'NRG Energy Inc',
'DXC Technology Co',
'Molson Coors Beverage Company Class B',
'Lumen Technologies Inc',
'News Corporation Class A',
'Peoples United Financial Inc',
'Campbell Soup Company',
'Organon & Co',
'Discovery Inc Class C',
'Franklin Resources Inc',
'Federal Realty Investment Trust',
'Penn National Gaming Inc',
'Mohawk Industries Inc',
'Norwegian Cruise Line Holdings Ltd',
'Invesco Ltd',
'DISH Network Corporation Class A',
'DaVita Inc',
'Pinnacle West Capital Corporation',
'Alaska Air Group Inc',
'Huntington Ingalls Industries Inc',
'PVH Corp',
'Rollins Inc',
'Vornado Realty Trust',
'Nielsen Holdings Plc',
'Ralph Lauren Corporation Class A',
'Fox Corporation Class B',
'IPG Photonics Corporation',
'Discovery Inc Class A',
'Under Armour Inc Class A',
'Under Armour Inc Class C',
'News Corporation Class B'
]

const zip = (...arr) => {
    const zippedFiles = [];
    arr.forEach((el, ind) => {
       el.forEach((el1, idx) => {
          if(!zippedFiles[idx]){
             zippedFiles[idx] = [];
          };
          if(!zippedFiles[idx][ind]){
             zippedFiles[idx][ind] = [];
          }
          zippedFiles[idx][ind] = el1 || '';
       })
    });
    return zippedFiles;
 };

export const searchOptions = zip(tickers, companyNames);
